DROP SCHEMA IF EXISTS apikamgusv2 CASCADE;
DROP SCHEMA IF EXISTS proyecto_legacy CASCADE;

CREATE SCHEMA apikamgusv2;
CREATE SCHEMA proyecto_legacy;

CREATE TABLE apikamgusv2.attribute_license (id bigserial PRIMARY KEY, status text);
CREATE TABLE apikamgusv2.cards (id bigserial PRIMARY KEY, status text, card_type text);
CREATE TABLE apikamgusv2.colors (id bigserial PRIMARY KEY, status text);
CREATE TABLE apikamgusv2.countries (id bigserial PRIMARY KEY, status text);
CREATE TABLE apikamgusv2.documents (id bigserial PRIMARY KEY, tipo text);
CREATE TABLE apikamgusv2.document_types (id bigserial PRIMARY KEY, status text);
CREATE TABLE apikamgusv2.drivers (id bigserial PRIMARY KEY, status text, status_driver text);
CREATE TABLE apikamgusv2.driver_accounts (id bigserial PRIMARY KEY, type text);
CREATE TABLE apikamgusv2.driver_services (id bigserial PRIMARY KEY, service_id bigint, driver_id bigint, status text, confirmed text, ispaid text);
CREATE TABLE apikamgusv2.driver_vehicles (id bigserial PRIMARY KEY, status text);
CREATE TABLE apikamgusv2.fcm_tokens (id bigserial PRIMARY KEY, platform text);
CREATE TABLE apikamgusv2.images (id bigserial PRIMARY KEY, "is" text);
CREATE TABLE apikamgusv2.licenses (id bigserial PRIMARY KEY, status text);
CREATE TABLE apikamgusv2.marks (id bigserial PRIMARY KEY, status text);
CREATE TABLE apikamgusv2.models (id bigserial PRIMARY KEY, status text);
CREATE TABLE apikamgusv2.qualifications (id bigserial PRIMARY KEY, status text);
CREATE TABLE apikamgusv2.services (id bigserial PRIMARY KEY, tipo_transporte text, tipo_servicio text, estado text, tipo_pago text, pago text);
CREATE TABLE apikamgusv2.service_statuses (id bigserial PRIMARY KEY, status text);
CREATE TABLE apikamgusv2.social_auth_token (id bigserial PRIMARY KEY, type text);
CREATE TABLE apikamgusv2.support_tickets (id bigserial PRIMARY KEY, priority text);
CREATE TABLE apikamgusv2.transactions (id bigserial PRIMARY KEY, type text, status text, gateway text);
CREATE TABLE apikamgusv2.users (id bigserial PRIMARY KEY, status text);
CREATE TABLE apikamgusv2.user_bonuses (id bigserial PRIMARY KEY, used text);

CREATE TABLE proyecto_legacy.bonos_usuario (id bigserial PRIMARY KEY, utilizado text);
CREATE TABLE proyecto_legacy.calificaciones (id bigserial PRIMARY KEY, estado text);
CREATE TABLE proyecto_legacy.codigos (id bigserial PRIMARY KEY, estado text);
CREATE TABLE proyecto_legacy.colores_automoviles (id bigserial PRIMARY KEY, estado text);
CREATE TABLE proyecto_legacy.conductores (id bigserial PRIMARY KEY, tipo_registro text, estado text);
CREATE TABLE proyecto_legacy.conductor_servicios (idconductor_servicios bigserial PRIMARY KEY, estado text, role text, ispagado text);
CREATE TABLE proyecto_legacy.marcas (id bigserial PRIMARY KEY, estado text);
CREATE TABLE proyecto_legacy.modelos (id bigserial PRIMARY KEY, estado text);
CREATE TABLE proyecto_legacy.objetos (id bigserial PRIMARY KEY, categoria text, estado text);
CREATE TABLE proyecto_legacy.paises (id bigserial PRIMARY KEY, habilita text);
CREATE TABLE proyecto_legacy.servicios (idservicios bigserial PRIMARY KEY, tipo_translado text, estado text, tipo_pago text, ispagado text);
CREATE TABLE proyecto_legacy.servicios_objetos (id bigserial PRIMARY KEY, estado text);
CREATE TABLE proyecto_legacy.tarjetas (id bigserial PRIMARY KEY, estado text);
CREATE TABLE proyecto_legacy.tipos_documento (id bigserial PRIMARY KEY, estado text);
CREATE TABLE proyecto_legacy.tipo_camion (id bigserial PRIMARY KEY, estado text);
CREATE TABLE proyecto_legacy.transacciones (id bigserial PRIMARY KEY, interfaz text);
CREATE TABLE proyecto_legacy.usuarios (idusuarios bigserial PRIMARY KEY, tipo_registro text, registro text);
CREATE TABLE proyecto_legacy.vehiculos (id bigserial PRIMARY KEY, estado text);

-- enum CHECK constraints extracted from apikamgusv2_pg.sql.
ALTER TABLE apikamgusv2.attribute_license ADD CONSTRAINT attribute_license_status_chk CHECK (status IN ('true', 'false')) NOT VALID;
ALTER TABLE apikamgusv2.cards ADD CONSTRAINT cards_status_chk CHECK (status IN ('A', 'I')) NOT VALID;
ALTER TABLE apikamgusv2.cards ADD CONSTRAINT cards_card_type_chk CHECK (card_type IN ('MasterCard', 'Visa')) NOT VALID;
ALTER TABLE apikamgusv2.colors ADD CONSTRAINT colors_status_chk CHECK (status IN ('A', 'I')) NOT VALID;
ALTER TABLE apikamgusv2.countries ADD CONSTRAINT countries_status_chk CHECK (status IN ('A', 'I')) NOT VALID;
ALTER TABLE apikamgusv2.documents ADD CONSTRAINT documents_tipo_chk CHECK (tipo IN ('CEDULA', 'PASAPORTE', 'LICENCIA')) NOT VALID;
ALTER TABLE apikamgusv2.document_types ADD CONSTRAINT document_types_status_chk CHECK (status IN ('ACTIVO', 'INACTIVO')) NOT VALID;
ALTER TABLE apikamgusv2.drivers ADD CONSTRAINT drivers_status_chk CHECK (status IN ('F', 'G', 'E')) NOT VALID;
ALTER TABLE apikamgusv2.drivers ADD CONSTRAINT drivers_status_driver_chk CHECK (status_driver IN ('A', 'I', 'P')) NOT VALID;
ALTER TABLE apikamgusv2.driver_accounts ADD CONSTRAINT driver_accounts_type_chk CHECK (type IN ('ahorros', 'corriente')) NOT VALID;
ALTER TABLE apikamgusv2.driver_services ADD CONSTRAINT driver_services_status_chk CHECK (status IN ('Pendiente', 'Terminado', 'En curso', 'Agendado', 'Rechazado')) NOT VALID;
ALTER TABLE apikamgusv2.driver_services ADD CONSTRAINT driver_services_confirmed_chk CHECK (confirmed IN ('SI', 'NO')) NOT VALID;
ALTER TABLE apikamgusv2.driver_services ADD CONSTRAINT driver_services_ispaid_chk CHECK (ispaid IN ('Pagado', 'Pendiente', 'Omitido', 'Pagado Kamgus')) NOT VALID;
ALTER TABLE apikamgusv2.driver_vehicles ADD CONSTRAINT driver_vehicles_status_chk CHECK (status IN ('P', 'I', 'A', 'R')) NOT VALID;
ALTER TABLE apikamgusv2.fcm_tokens ADD CONSTRAINT fcm_tokens_platform_chk CHECK (platform IN ('web', 'ios', 'android')) NOT VALID;
ALTER TABLE apikamgusv2.images ADD CONSTRAINT images_is_chk CHECK ("is" IN ('profile', 'photo_url_vehicle', 'back_url_vehicle', 'right_url_vehicle', 'left_url_vehicle', 'property_url_vehicle', 'revised_url_vehicle', 'policy_url_vehicle', 'service_detail', 'service_point_A', 'service_point_B', 'service_point_C', 'service_point_D', 'service_point_E', 'service_point_FI', 'point', 'support')) NOT VALID;
ALTER TABLE apikamgusv2.licenses ADD CONSTRAINT licenses_status_chk CHECK (status IN ('A', 'I')) NOT VALID;
ALTER TABLE apikamgusv2.marks ADD CONSTRAINT marks_status_chk CHECK (status IN ('A', 'I')) NOT VALID;
ALTER TABLE apikamgusv2.models ADD CONSTRAINT models_status_chk CHECK (status IN ('A', 'I')) NOT VALID;
ALTER TABLE apikamgusv2.qualifications ADD CONSTRAINT qualifications_status_chk CHECK (status IN ('A', 'I')) NOT VALID;
ALTER TABLE apikamgusv2.services ADD CONSTRAINT services_tipo_transporte_chk CHECK (tipo_transporte IN ('MOTO', 'SEDAN', 'PANEL', 'PICK UP', 'CAMIÓN PEQUEÑO', 'CAMIÓN GRANDE')) NOT VALID;
ALTER TABLE apikamgusv2.services ADD CONSTRAINT services_tipo_servicio_chk CHECK (tipo_servicio IN ('SIMPLE', 'MUDANZA')) NOT VALID;
ALTER TABLE apikamgusv2.services ADD CONSTRAINT services_estado_chk CHECK (estado IN ('ACTIVO', 'AGENDADO', 'INACTIVO', 'PENDIENTE', 'CANCELADO', 'ANULADO', 'TERMINADO', 'RESERVA', 'PROGRAMAR', 'REPETIR')) NOT VALID;
ALTER TABLE apikamgusv2.services ADD CONSTRAINT services_tipo_pago_chk CHECK (tipo_pago IN ('transferencia', 'Card', 'Efectivo', 'Yappy')) NOT VALID;
ALTER TABLE apikamgusv2.services ADD CONSTRAINT services_pago_chk CHECK (pago IN ('PENDIENTE', 'PAGADO', 'ANULADO', 'TRANSFERIDO')) NOT VALID;
ALTER TABLE apikamgusv2.service_statuses ADD CONSTRAINT service_statuses_status_chk CHECK (status IN ('Nuevo servicio', 'Servicio rechazado', 'Estado de servicio', 'Conductor activo', 'Llego al punto B', 'Descargado', 'Servicio finalizado')) NOT VALID;
ALTER TABLE apikamgusv2.social_auth_token ADD CONSTRAINT social_auth_token_type_chk CHECK (type IN ('Facebook', 'Apple')) NOT VALID;
ALTER TABLE apikamgusv2.support_tickets ADD CONSTRAINT support_tickets_priority_chk CHECK (priority IN ('low', 'medium', 'high')) NOT VALID;
ALTER TABLE apikamgusv2.transactions ADD CONSTRAINT transactions_type_chk CHECK (type IN ('mastercard', 'amex', 'visa', 'discover')) NOT VALID;
ALTER TABLE apikamgusv2.transactions ADD CONSTRAINT transactions_status_chk CHECK (status IN ('succeeded', 'pending', 'failed', 'requires_payment_method', 'requires_confirmation', 'requires_action', 'processing', 'requires_capture', 'canceled', 'preordered', 'open', 'complete')) NOT VALID;
ALTER TABLE apikamgusv2.transactions ADD CONSTRAINT transactions_gateway_chk CHECK (gateway IN ('metro', 'transferencia', 'stripe', 'yappy', 'pago_cash')) NOT VALID;
ALTER TABLE apikamgusv2.users ADD CONSTRAINT users_status_chk CHECK (status IN ('En revision', 'Activo', 'In activo', 'Bloqueado', 'Eliminado')) NOT VALID;
ALTER TABLE apikamgusv2.user_bonuses ADD CONSTRAINT user_bonuses_used_chk CHECK (used IN ('SI', 'NO')) NOT VALID;

-- enum CHECK constraints extracted from proyecto_legacy_pg.sql.
ALTER TABLE proyecto_legacy.bonos_usuario ADD CONSTRAINT bonos_usuario_utilizado_chk CHECK (utilizado IN ('NO', 'SI')) NOT VALID;
ALTER TABLE proyecto_legacy.calificaciones ADD CONSTRAINT calificaciones_estado_chk CHECK (estado IN ('A', 'I')) NOT VALID;
ALTER TABLE proyecto_legacy.codigos ADD CONSTRAINT codigos_estado_chk CHECK (estado IN ('A', 'I', 'E')) NOT VALID;
ALTER TABLE proyecto_legacy.colores_automoviles ADD CONSTRAINT colores_automoviles_estado_chk CHECK (estado IN ('A', 'I')) NOT VALID;
ALTER TABLE proyecto_legacy.conductores ADD CONSTRAINT conductores_tipo_registro_chk CHECK (tipo_registro IN ('F', 'G', 'E')) NOT VALID;
ALTER TABLE proyecto_legacy.conductores ADD CONSTRAINT conductores_estado_chk CHECK (estado IN ('A', 'I', 'P')) NOT VALID;
ALTER TABLE proyecto_legacy.conductor_servicios ADD CONSTRAINT conductor_servicios_estado_chk CHECK (estado IN ('Rechazado', 'En Curso', 'Pendiente', 'Terminado', 'Agendado')) NOT VALID;
ALTER TABLE proyecto_legacy.conductor_servicios ADD CONSTRAINT conductor_servicios_role_chk CHECK (role IN ('USUARIO', 'CONDUCTOR', 'ADMIN')) NOT VALID;
ALTER TABLE proyecto_legacy.conductor_servicios ADD CONSTRAINT conductor_servicios_ispagado_chk CHECK (ispagado IN ('Pendiente', 'Pagado', 'Omitido', 'Pagado Kamgus')) NOT VALID;
ALTER TABLE proyecto_legacy.marcas ADD CONSTRAINT marcas_estado_chk CHECK (estado IN ('A', 'I')) NOT VALID;
ALTER TABLE proyecto_legacy.modelos ADD CONSTRAINT modelos_estado_chk CHECK (estado IN ('A', 'I')) NOT VALID;
ALTER TABLE proyecto_legacy.objetos ADD CONSTRAINT objetos_categoria_chk CHECK (categoria IN ('Habitación', 'Sala', 'Comedor', 'Cocina', 'Estudio', 'Maquinas', 'Televisores', 'Cajas y Bolsas')) NOT VALID;
ALTER TABLE proyecto_legacy.objetos ADD CONSTRAINT objetos_estado_chk CHECK (estado IN ('A', 'I')) NOT VALID;
ALTER TABLE proyecto_legacy.paises ADD CONSTRAINT paises_habilita_chk CHECK (habilita IN ('A', 'I')) NOT VALID;
ALTER TABLE proyecto_legacy.servicios ADD CONSTRAINT servicios_tipo_translado_chk CHECK (tipo_translado IN ('Simple', 'Mudanza')) NOT VALID;
ALTER TABLE proyecto_legacy.servicios ADD CONSTRAINT servicios_estado_chk CHECK (estado IN ('Activo', 'Agendado', 'Inactivo', 'Pendiente', 'Cancelado', 'Anulado', 'Terminado', 'Reserva', 'Programar', 'Repetir')) NOT VALID;
ALTER TABLE proyecto_legacy.servicios ADD CONSTRAINT servicios_tipo_pago_chk CHECK (tipo_pago IN ('Efectivo', 'Tarjeta Crédito', 'Transferencia', 'Yappy')) NOT VALID;
ALTER TABLE proyecto_legacy.servicios ADD CONSTRAINT servicios_ispagado_chk CHECK (ispagado IN ('PENDIENTE', 'PAGADO', 'ANULADO', 'TRANSFERIDO')) NOT VALID;
ALTER TABLE proyecto_legacy.servicios_objetos ADD CONSTRAINT servicios_objetos_estado_chk CHECK (estado IN ('A', 'I')) NOT VALID;
ALTER TABLE proyecto_legacy.tarjetas ADD CONSTRAINT tarjetas_estado_chk CHECK (estado IN ('A', 'I')) NOT VALID;
ALTER TABLE proyecto_legacy.tipos_documento ADD CONSTRAINT tipos_documento_estado_chk CHECK (estado IN ('A', 'I')) NOT VALID;
ALTER TABLE proyecto_legacy.tipo_camion ADD CONSTRAINT tipo_camion_estado_chk CHECK (estado IN ('A', 'I')) NOT VALID;
ALTER TABLE proyecto_legacy.transacciones ADD CONSTRAINT transacciones_interfaz_chk CHECK (interfaz IN ('TERMINAR', 'PREAUTORIZACION', 'NOPAGOEFECTIVO', 'DEVOLVER', 'DEVOLVER50', 'CONFIRMARSERVICIO')) NOT VALID;
ALTER TABLE proyecto_legacy.usuarios ADD CONSTRAINT usuarios_tipo_registro_chk CHECK (tipo_registro IN ('F', 'G', 'E', 'TEMP')) NOT VALID;
ALTER TABLE proyecto_legacy.usuarios ADD CONSTRAINT usuarios_registro_chk CHECK (registro IN ('APP_WEB_KAMG', 'WEB_U', 'APP_C', 'WEB_C', 'APP_U', 'FACEBOOK', 'APPLE', 'WEB_I')) NOT VALID;
ALTER TABLE proyecto_legacy.vehiculos ADD CONSTRAINT vehiculos_estado_chk CHECK (estado IN ('A', 'I', 'R')) NOT VALID;
